name: 'Changelog Auto Add'
on:
    pull_request_target:
        types: [opened, synchronize, reopened, edited]
        paths-ignore:
          - 'docs/**'
          - '**/changelog/**'
          - '**/changelog.txt'
          - '.husky/**'
          - '.cursor/**'
          - '.github/**'
          - '!.github/workflows/changelog-auto-add.yml'
    workflow_dispatch:
        inputs:
            prNumber:
                description: Pull request number
                required: true
concurrency:
    group: changelog-auto-add-${{ github.event_name }}-${{ github.event.number || inputs.prNumber }}
    cancel-in-progress: true

env:
  GIT_COMMITTER_NAME: 'woocommercebot'
  GIT_COMMITTER_EMAIL: 'woocommercebot@users.noreply.github.com'
  GIT_AUTHOR_NAME: 'woocommercebot'
  GIT_AUTHOR_EMAIL: 'woocommercebot@users.noreply.github.com'

jobs:
    add-changelog:
        name: 'Add changelog to PR'
        if: ${{ github.event.pull_request.user.login != 'github-actions[bot]' && github.event.pull_request.user.login != 'woocommercebot' && ( github.event_name != 'pull_request_target' || contains( github.event.pull_request.body, '[x] Automatically create a changelog' ) ) }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version-file: '.nvmrc'

            - name: Setup PNPM
              uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

            - name: Generate Changelog File
              env:
                  GITHUB_TOKEN: ${{ secrets.WC_BOT_PR_CREATE_TOKEN || secrets.GITHUB_TOKEN }}
              run: pnpm utils changefile ${{ github.event.number || inputs.prNumber }} -o ${{ github.repository_owner }}
